data-path="/opt/besu/data"
genesis-file="/opt/besu/genesis.json"
node-private-key-file="/opt/besu/key"

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["all"]
rpc-http-api=["ETH","NET","WEB3","QBFT","ADMIN","TXPOOL"]

host-allowlist=["*"]

p2p-enabled=true
discovery-enabled=true

min-gas-price=0
revert-reason-enabled=true
